### ISSUE TITLE
Add nightlies

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-workstation-ci#39]
Per chat with @zenmonkeykstop it would be useful to add a nightly job in addition to the per-PR job so that we can catch breakage that may impact prod (e.g., due to an upstream package being updated in dom0) even when there's no active development on `main`.

**Comment by eloquence** [comment]
Questions:
- Are we currently automatically running `qubes-dom0-update`, implicitly as part of the provisioning run, or separately, on a regular basis?
- What would be the best way to report back the result of a nightly run failure, e.g., to Slack and/or GitHub?

**Comment by eloquence** [comment]
Thanks @mig5.  Not sure how feasible an unattended upgrade + reboot + login cycle is as part of a nightly build with the current setup. My take is if we can get a quick win here, it's worth it, but otherwise we should defer it and consider it as part of the next generation of this infra.

Le's discuss this in our planning mtg tomorrow as part of the larger CI epic.

**Comment by mig5** [comment]
@eloquence @zenmonkeykstop 

As part of the next generation of SDW CI testing, I have added the ability to perform nightlies, which first perform dom0 and template updates, followed by a reboot before proceeding with the CI process.

It goes like this:

1) (programatically obtain the latest commit of the SDW repo)
2) ./magic.py --version $VERSION --commit $COMMITHASH --snapshot $SNAPSHOTID --update

Abridged output to give you the idea:
```
Using machine Qubes 4.2 A for CI
First reverting Qubes 4.2 A to snapshot 2024021401
Now powering on Qubes 4.2 A
VM Qubes 4.2 A is not powered on, waiting
VM Qubes 4.2 A is now powered on, waiting 1 minute to let it finish booting
VM Qubes 4.2 A is now ready, moving on with next steps
Applying updates on Qubes 4.2 A first before commencing CI
Updating dom0...
Program running, PID is 3513
Program running, PID is 3513
Program running, PID is 3513
<snip>
Program 3513 completed with success
Updating templates...
Program running, PID is 3800
Program running, PID is 3800
Program running, PID is 3800
<snip>
Program 3800 completed with success
Rebooting Qubes 4.2 A
<snip>
Commencing the CI executing on Qubes 4.2 A
<test suite follows as normal>
```

We'll be able to run this simply as a nightly cron job for 4.1 or 4.2 or both.

**Comment by mig5** [comment]
I'm going to close this, as nightlies are now in place for the `main` branch, as of https://github.com/freedomofpress/infrastructure/pull/4659 and https://github.com/freedomofpress/securedrop-workstation-ci/pull/40

With main branch's .yml file set to Qubes version 4.1, that's the version that will get nightlies run against it, using the latest commit in that branch.

@zenmonkeykstop, once you have a branch for `4.2` (or the reverse, perhaps you'll move 4.1 stuff to its own branch and treat `main` as 4.2), let me know, and I can add another nightly job for testing the relevant version/branch.

**Comment by mig5** [comment]
Actually @zenmonkeykstop, one question re nightlies: right now, the nightly run will just post the commit status to the latest commit in `main` (with the log file link as usual). So on each night, the commit status will sort of 'clobber' the previous one (though you'll always have the logs available at https://ws-ci-runner.securedrop.org from the previous nights)

Are you wanting some more verbose feedback of the reuslt of nightlies, e.g Slack notifications? Do you want them just if the build failed, etc?

**Comment by legoktm** [comment]
Maybe I missed it somewhere, but is there a reason we're using a webhook/custom status check type system instead of having a GHA job log into the machine and kick off the job? Or even possibly a self-hosted GHA runner? Using GHA would make it easy to see past runs, automatically take care of storing logs, retry UI, etc.

**Comment by mig5** [comment]
@legoktm I think there are several related reasons (none of them fixed):

1) It is a vestige of the original CI, where it was running on a laptop that wasn't accessible remotely except via Tailscale. The process of the webhook's payload getting onto the system and the logs that result, have not changed from the original CI that's been in place for over a year. The initial 'nightlies' idea was to just 'hook into' that system.
2) We already use the github webhook python flask library in other areas of FPF infra (packaging etc)
3) Changing this part of the CI (how the Github event finds its way to the platform that runs CI) was not part of the scope for refactoring (the focus was on: Adding 4.2 support, adding parallel builds, adding a proper clean restore rather than manual cleanup/uninstall, and some stretch goals (nightlies, automated patching)
4) The project is kind of cursed in that the person working on the project does it the way they know how, and only afterwards do others come in asking 'why did you do it like that' :) (To be clear: no problem asking, just that we seem to lose input from others during the earlier planning of 'this is what we're going to do'). It strikes me that the most capable people never are the ones who end up working on the changes, the result is inevitably an MVP.

I have never used GHA and I have some qualms about the idea of letting it SSH into our server(s) and doing stuff (I guess that's the idea of where the runner could come in). But I also definitely see the merit in what you're suggesting (it doesn't answer the question of notifications but we could maybe add that in later)

But I'll discuss with the infra team, and also as to whether there's budget to redo it all, we spent a lot of hours on it this quarter already.

**Comment by legoktm** [comment]
Makes sense and sorry for being the one showing up late 😅 . I can split this idea into a different issue as a feature request if you'd like.

> (it doesn't answer the question of notifications but we could maybe add that in later)

Oh I forgot to mention that part; GH's Slack integration supports subscribing to workflows (https://github.com/integrations/slack?tab=readme-ov-file#actions-workflow-notifications), we have it set in both DZ and SD notifications channels.

To answer the original question you had asked...

> Are you wanting some more verbose feedback of the result of nightlies, e.g Slack notifications? Do you want them just if the build failed, etc?

Yes, I think that would be ideal. I think Slack is better but no personal preference on whether it's every night or just on success.

**Comment by mig5** [comment]
Hi @legoktm. After discussion with the infra team, indeed we are going to treat the idea of GHA as the invoker of CI as a separate (future) task for consideration, as it was not previously discussed or scoped for (Q1 was very much a 'lift and shift' of the original CI with some additional enhancements). I'll open a separate story for that in due course.

I'll try and get Slack notifications for the nightlies as a stopgap in the short to medium term (and maybe will make it so that it doesn't continually 'clobber' the commit status on the latest commit every night, which serves little benefit, but you'll still always get the log)

**Comment by mig5** [comment]
Slack notifications are now in place for when builds fail/error - not just for nightlies but regular CI too - handled in https://github.com/freedomofpress/securedrop-workstation-ci/pull/40

**Comment by legoktm** [comment]
Awesome, ty!

One small thing - based on the log, it looks like the nightly run starts around 5:10 (UTC I assume). We build nightly packages at 6:00 UTC:
https://github.com/freedomofpress/securedrop-client/blob/a4fbac483d4c284d39c4f243afc360f484535c15/.github/workflows/nightlies.yml#L4

It takes about 6-7 minutes to build, so they're usually on apt-test by like 6:07. Do you think we could have the sdw nightly run start at 6:30 UTC instead? If it's difficult to change, we can pretty trivally move the client nightly package builds to be earlier.

**Comment by mig5** [comment]
No worries - nightlies now run at 6:30AM. Also, I moved the other crons that apply automatic Qubes (dom0, template and standalone) updates (followed by taking a new snapshot to be used for future CI runs) to take place earlier (around 3 - 4:30AM). So that should mean the nightly CI is taking place on an up-to-date Qubes.
